# Generated by Django 2.2.6 on 2019-10-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='committee',
            fields=[
                ('committeeName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('memberCount', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LendBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenderusername', models.CharField(default='NONE', max_length=20)),
                ('borrowerusername', models.CharField(default='NONE', max_length=20)),
                ('transaction', models.IntegerField(default=0)),
                ('duedate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='lendcommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committeeName', models.CharField(max_length=20)),
                ('username', models.CharField(default=0, max_length=20)),
                ('moneyLended', models.IntegerField(default=0)),
                ('duedate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='lendStartup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('startup', models.CharField(max_length=20)),
                ('moneyLended', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='startStartup',
            fields=[
                ('startup', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('moneyNeeded', models.IntegerField(default=0)),
                ('moneyBorrowed', models.IntegerField(default=0)),
                ('Investors', models.IntegerField(default=0)),
            ],
        ),
    ]
